spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC
    username: "root"
    password: "root1234!@"
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/inter_face
      database: inter_face
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true



#  redis:
#    host: localhost
#    port: 6379
#    password: redis_pw
#    lettuce:
#      pool:
#        pool 설정
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#    timeout: 2000